# This part creates a load balancer pod that receives traffic from
# internet and load-balances to our pods
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app     # This makes load balancer point to todo-app deployment
  ports:
    - port: 80        
      targetPort: 80  # The port our container(in pods) listens to
  type: LoadBalancer
---

# This part creates a pod that runs our docker image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  # we only want one replica of our container for now
  replicas: 1  
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: nishants/todo_app:v0.1   # Our docker image on docker hub
          ports:
            - containerPort: 80           # Port that our app listens to
          env:
            - name: TODO_APP_MongoSettings__ConnectionString
              value: mongodb://mongo-service:27017/dev # mongo-service that exposes mongo db to us
          imagePullPolicy: Always